name: testing

on:
  pull_request:
    branches:
      - master

jobs:
  lint-testing:
    name: Lint Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone Repo
        uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Lint code
      - name: Run Android Linter
        run: ./gradlew lintDebug

  unit-testing:
    name: Unit Testing
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Run unit tests
      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

  apk-building:
    name: Generate APK's
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Assemble debug APK
        run: ./gradlew assembleDebug 

      - name: Upload debug APK
        uses: actions/upload-artifact@v1
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Assemble debug instrumental test APK
        run: ./gradlew assembleDebugAndroidTest 

      - name: Upload debug instrumental test APK
        uses: actions/upload-artifact@v1
        with:
          name: app-debug-androidTest
          path: app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk

  firebase-ui-testing:
    name: Run UI tests with Firebase Test Lab
    needs: apk-building
    runs-on: ubuntu-latest

    steps:    
      - uses: actions/checkout@v1

      - name: Download debug APK
        uses: actions/download-artifact@v1
        with:
          name: app-debug

      - name: Download debug instrumental test APK
        uses: actions/download-artifact@v1
        with:
          name: app-debug-androidTest

      - name: Login to Google Cloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with: 
          service_account_key: ${{ secrets.GCLOUD_AUTH }}

      - name: Set current project
        run: gcloud config set project ${{ secrets.FIREBASE_PROJECT_ID }}
        
      - name: Run Instrumentation Tests in Firebase Test Lab
        run: gcloud firebase test android run --type instrumentation --app app-debug/app-debug.apk --test app-debug-androidTest/app-debug-androidTest.apk --device model=Pixel2,version=28,locale=pl,orientation=portrait