name: testing

on:
  pull_request:
    branches:
      - master

jobs:
  lint-testing:
    name: Lint Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone Repo
        uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Lint code
      - name: Run Android Linter
        run: ./gradlew lintDebug

  unit-testing:
    name: Unit Testing
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Run unit tests
      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

  apk-building:
    name: Generate APK's
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Assemble debug APK
        run: ./gradlew assembleDebug 

      - name: Upload debug APK
        uses: actions/upload-artifact@v1
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Assemble debug instrumental test APK
        run: ./gradlew assembleDebugAndroidTest 

      - name: Upload debug instrumental test APK
        uses: actions/upload-artifact@v1
        with:
          name: app-debug-androidTest
          path: app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
