name: testing

on:
  pull_request:
    branches:
      - master

jobs:
  testing:
    name: Lint Check and Testing

    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Lint code
      - name: Run Android Linter
        run: ./gradlew lintDebug

      # Run unit tests
      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest
